name: Bug
description: Reportar um comportamento incorreto
title: '[Bug]: '
labels: ['bug']
body:
  - type: textarea
    id: description
    attributes:
      label: Descrição
      description: O que está acontecendo de errado.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Passos para reproduzir
      description: Sequência para chegar ao bug.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento esperado
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Comportamento atual
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Ambiente / Evidências
      description: Navegador, SO, screenshots ou vídeos, se aplicável.
    validations:
      required: false
